//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cackle.ConsoleApp.Extensions.Logging.SpectreConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cackle_ConsoleApp_Extensions_Logging_SpectreConsole {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cackle_ConsoleApp_Extensions_Logging_SpectreConsole() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cackle.ConsoleApp.Extensions.Logging.SpectreConsole.Cackle.ConsoleApp.Extensions." +
                            "Logging.SpectreConsole", typeof(Cackle_ConsoleApp_Extensions_Logging_SpectreConsole).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum queue length ({0}) for the SpectreConsole logger must be greater than 0..
        /// </summary>
        internal static string ArgumentOutOfRange_MaxQueueLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MaxQueueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue modes ({0}) supported by SpectreConsole is Wait or DropWrite..
        /// </summary>
        internal static string ArgumentOutOfRangeException_QueueFullMode {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_QueueFullMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages have been dropped from the logging queue..
        /// </summary>
        internal static string Warning_MessagesDropped {
            get {
                return ResourceManager.GetString("Warning_MessagesDropped", resourceCulture);
            }
        }
    }
}
